### ISSUE TITLE
Khabase Python3 compatibility issue

### ISSUE THREAD

**Issue by Walid47** [mboukhalfa/Khabaze#1]
When **Khabaze** is used with ```Python3``` it needs to rename the *.so file

**Comment by mboukhalfa** [comment]
I have tried to rename the compiled outputs, however our submodules raise errors `no module named  submodule` since the compiler rename imports into the original output name. I think it will be better to keep the compiler output names and update the main file. I will commit the current changes in case you need to test, I have also joined test modules. I will continue working on the issue.

**Comment by mboukhalfa** [comment]
suddenly it works fine with python3 .. ! In fact I deployed SM after compiling some modules and I did not realize that it was written with python3 ! days after I was thinking to migrate my code to python3 this issue pop up in my mind  then I realized : I have already deployed a service with python3 you cannot imagine how was that confusing... I will close the issue 👍 when you do everything right and you do not know
